# Generated by Django 4.0.4 on 2022-05-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bag name')),
                ('about', models.TextField(verbose_name='Bag about')),
                ('price', models.IntegerField(verbose_name='Bag price')),
                ('img', models.ImageField(upload_to='media', verbose_name='Bag image')),
            ],
            options={
                'verbose_name': 'Bag',
                'verbose_name_plural': 'Bags',
            },
        ),
    ]
